#!/bin/sh
### BEGIN INIT INFO
# Short-Description: Create directory in userdata
# Description:       This script creates a directory in userdata if it does not exist.
### END INIT INFO

USERDATA_DIR="/userdata/update"

case "$1" in
    start)
        if [ ! -d "$USERDATA_DIR" ]; then
            mkdir -p "$USERDATA_DIR"
            echo "Created directory: $USERDATA_DIR"
        fi
        ;;
    stop)
        # No action on stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0

